baseURL = 'https://p3land.smallkirby.com'
languageCode = 'jp'
title = 'P3LAND'
description = 'PPP LAND'

sidebar_search_disable = false

enableGitInfo = true
contentDir = 'content'

[params]
copyright = 'smallkirby'
description = "P3LAND: Dreaming of Necropolis"
github_repo = 'https://github.com/smallkirby/p3land'
github_branch = 'master'
offlineSearch = true
prism_syntax_highlighting = false
navbar_logo = true

[params.ui]
sidebar_menu_compact = true
breadcrumb_disable = false

[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/smallkirby"
	icon = "fab fa-twitter"

[[params.links.user]]
	name = "GitHub"
	url = "https://github.com/smallkirby"
	icon = "fab fa-github"

[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/smallkirby/p3land"
	icon = "fab fa-github"

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[outputs]
section = ["HTML", "RSS"]
